### ISSUE TITLE
proper python version?

### ISSUE THREAD

**Issue by lkcp** [AISyLab/AISY_Framework#1]
like tf2.0 is not support for python==3.8

I think it will be a good idea to indicate proper python version in README.md

**Comment by AISyLab** [comment]
Hi Jul1anWang,
Thank you for informing us about this missing detail. If you find any issues, please, do not hesitate in contacting us. 
I updated the readme.md file.
Best regards

**Comment by lkcp** [comment]
Hi,
You are welcome, it's my pleasure.
This frame is a really great news for SCA community, hopefully we can make it better together!
Best regards!
